### ISSUE TITLE
What font does this work with?

### ISSUE THREAD

**Issue by Fryie** [oh-my-fish/theme-es#5]
I've tried a number of the fonts from https://github.com/powerline/fonts, but haven't found any that contains the necessary glyphs for e.g. the Node or the Ruby icon. What font could I use instead?

**Comment by eugenesvk** [comment]
Yep, as far as I remember, the fonts you linked only contain ~5 additional glyphs. The additionaly glyphs I'm using are coming from other glyph sets. You can get some of the fonts with these glyph sets (or use the script to patch your favorite font yourself if it's not there) from here https://github.com/ryanoasis/nerd-fonts, use the complete version.

However, the glyph reference points are likely going to change in the future version of those Nerd fonts and my theme to make some of the more widespread codepoints in their default place on conflict. Just FYI in case you'll notice wrong glyphs on theme update (I'll put a warning in the new version description)

**Comment by chalme** [comment]
@Fryie  yes,  @eugenesvk  is  true,    I try it successfully.   it need  [these glyph](https://github.com/primer/octicons).  you should use [font-patcher](https://github.com/ryanoasis/nerd-fonts) to add these glyph.

**Comment by eugenesvk** [comment]
Added a reference to the Nerd Fonts project to the readme
