### ISSUE TITLE
If I open a new shell the first git repo I hit errors

### ISSUE THREAD

**Issue by chopfitzroy** [oh-my-fish/theme-es#8]
In a new session the first git repo I open shows the following error:  
`test: Missing argument at index 2` If I then `cd` out and back in no error, or if I `cd` into another repo no error.

Cheers,
Otis.

**Comment by tomisacat** [comment]
Me came across the same problem. 
![1](https://cloud.githubusercontent.com/assets/1179735/18698204/d1db271e-7ffa-11e6-9f9f-20ee312a78da.png)
![2](https://cloud.githubusercontent.com/assets/1179735/18698205/d1e0bc06-7ffa-11e6-85c7-c2f5a36c7b47.png)

**Comment by tomisacat** [comment]
And you could notice that the icon is incorrect for git status, which powerline fonts suits for the theme?  Thanks.

**Comment by ahammond** [comment]
I have the same issue. Running OSX 10.11.6

**Comment by chalme** [comment]
@CrashyBang @tomisacat @ahammond Today I read the code, I find out this issus.
![1](https://cloud.githubusercontent.com/assets/17763926/21719024/5bf57134-d456-11e6-95e9-14f15b81fd54.png)
look at the picture,  the line 45 is commented, it will work .   you can test your code.

**Comment by RoToRx88** [comment]
@chalme I have the same problem as above after editing the file as you said.
Any idea where it can come from?

**Comment by eugenesvk** [comment]
I've updated the checks to not error out if something is missing in the latest theme version, let me know if it's still an issue

That happens only when in a git repo because the theme only showed various env versions in git repos
